kind: Service
apiVersion: v1
metadata:
  name: kdemo-svc
  labels:
    visualize: 'true'
spec:
  selector:
    name: kdemo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
